sudo: required
services:
  - docker
before_install:
  - docker build -t jeremymiller/life-elixir .
  - docker pull jeremymiller/node-lint
script:
  - docker run -it --rm --env MIX_ENV=dev jeremymiller/life-elixir mix hex.outdated
  - docker run -it --rm --env MIX_ENV=dev jeremymiller/life-elixir mix credo --strict
  - docker run -it --rm --env MIX_ENV=dev jeremymiller/life-elixir mix dialyzer --no-compile --no-check --halt-exit-status
  - docker run -it --rm --env MIX_ENV=test jeremymiller/life-elixir mix test
  - docker run -it --rm -v $PWD:/usr/src/app jeremymiller/node-lint dockerfile_lint -r .dockerfilelintrc -f app/Dockerfile
  - docker run -it --rm -v $PWD:/usr/src/app jeremymiller/node-lint eslint app/apps/interface/asstes/js/app.js
  - docker run -it --rm -v $PWD:/usr/src/app jeremymiller/node-lint markdownlint app/README.md
  - docker run -it --rm -v $PWD:/usr/src/app jeremymiller/node-lint stylelint app/apps/interface/assets/css/app.css
after_success:
  - docker run -it --rm --env MIX_ENV=test jeremymiller/life-elixir mix do compile --warnings-as-errors, coveralls.json
  - docker run -it --rm --env MIX_ENV=test jeremymiller/life-elixir bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN
