sudo: required
services:
  - docker
before_install:
  - docker build -t jeremymiller/life-elixir .
script:
  - docker run -it --rm --env MIX_ENV=dev jeremymiller/life-elixir mix hex.outdated
  - docker run -it --rm --env MIX_ENV=dev jeremymiller/life-elixir mix credo --strict
  - docker run -it --rm --env MIX_ENV=dev jeremymiller/life-elixir mix dialyzer --no-compile --no-check --halt-exit-status
  - docker run -it --rm --env MIX_ENV=test jeremymiller/life-elixir mix test
after_success:
  - docker run -it --rm --env MIX_ENV=docs jeremymiller/life-elixir mix inch.report --pedantic
