sudo: required
services:
  - docker
before_install:
  - docker pull jeremymiller/life-elixir
  - docker build -t jeremymiller/life-elixir .
  - docker pull jeremymiller/node-lint
script:
  - docker run -it --rm --env MIX_ENV=dev jeremymiller/life-elixir mix hex.outdated
  - docker run -it --rm --env MIX_ENV=dev jeremymiller/life-elixir mix credo --strict
  - docker run -it --rm --env MIX_ENV=dev jeremymiller/life-elixir mix dialyzer --no-compile --no-check --halt-exit-status
  - docker run -it --rm --env MIX_ENV=test jeremymiller/life-elixir mix test
  - docker run -it --rm -v $PWD:/usr/src/app jeremymiller/node-lint markdownlint app/README.md
  - docker run -it --rm -v $PWD:/usr/src/app jeremymiller/node-lint dockerfile_lint -r .dockerfilelintrc -f app/Dockerfile
after_success:
  - docker run -it --rm --env MIX_ENV=docs jeremymiller/life-elixir mix inch.report --pedantic
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - docker push jeremymiller/life-elixir
