sudo: required
services:
  - docker
before_install:
  - docker build -t jeremymiller/life-elixir .
script:
  - docker run -it --rm jeremymiller/life-elixir mix hex.outdated
  - docker run -it --rm jeremymiller/life-elixir mix credo
  - docker run -it --rm jeremymiller/life-elixir mix test
after_script:
  - MIX_ENV=docs mix deps.get
  - MIX_ENV=docs mix inch.report