sudo: required
services:
  - docker
env:
  - ELIXIR_VERSION=1.4.5 OTP_RELEASE=19.3
before_install:
  - docker build -t jeremymiller/life-elixir .
before_script:
  # Set PLT download location
  - export PLT_FILENAME=elixir-${ELIXIR_VERSION}_${OTP_RELEASE}.plt
  - export PLT_LOCATION=/home/travis/$PLT_FILENAME
  # Download PLT from danielberkompas/travis_elixir_plts on Github, store in $PLT_LOCATION
  - wget -O $PLT_LOCATION https://raw.github.com/danielberkompas/travis_elixir_plts/master/$PLT_FILENAME
script:
  - docker run -it --rm jeremymiller/life-elixir mix hex.outdated
  - docker run -it --rm jeremymiller/life-elixir mix credo
  - docker run -it --rm jeremymiller/life-elixir mix test
  - docker run -it --rm jeremymiller/life-elixir mix dialyzer --no_check_plt --plt $PLT_LOCATION --no_native _build/test/lib/life_elixir/ebin
after_success:
  - docker run -it --rm --env MIX_ENV=docs jeremymiller/life-elixir mix inch.report --pedantic