sudo: required
services:
  - docker
before_install:
  - docker build -t jeremymiller/life-elixir .
script:
  - docker run -it --rm jeremymiller/life-elixir mix credo
  - docker run -it --rm jeremymiller/life-elixir mix test